version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "master"
    pull-request-branch-name:
      separator: "-"
    versioning-strategy: increase
